name: test-upload-file

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Download assess URL."
        required: true
        type: string
      filename:
        description: "Download assess filename."
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Download Software
        run: |
          sudo apt-get install aria2
      - name: Download File
        run: aria2c -o ${{ inputs.filename }} ${{ inputs.url }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: test
          files: "${{ inputs.filename }}"
